eureka:
    client: 
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
search: http://localhost:8111/searchflight/
flightDetails: http://localhost:8888/flightservice/
flightCatalog: http://localhost:8181/flightcatalog
