eureka:
    client: 
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
user.service.url=http://localhost:8081/userService/checkRest     
